# Generated by Django 3.2.6 on 2023-07-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_citas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.CharField(max_length=15, verbose_name='Fecha de cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de cita')),
                ('lugar_cita', models.CharField(max_length=20, verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'Cita',
                'ordering': ['id_citas'],
            },
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_estado_civil', models.CharField(max_length=10, verbose_name='Estado Civil')),
                ('condicion_estado_civil', models.BooleanField(verbose_name='Condicion')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estado Civil',
                'db_table': 'Estado_Civil',
                'ordering': ['descripcion_estado_civil'],
            },
        ),
        migrations.CreateModel(
            name='Lugar_Nacimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubigeo', models.CharField(max_length=6, verbose_name='Ubigeo')),
                ('distrito', models.CharField(max_length=20, verbose_name='Distrito')),
                ('provincia', models.CharField(max_length=20, verbose_name='Provincia')),
                ('departamento', models.CharField(max_length=20, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Lugar_Nacimiento',
                'verbose_name_plural': 'Lugar_Nacimiento',
                'db_table': 'Lugar_Nacimiento',
                'ordering': ['ubigeo', '-distrito'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni_personal', models.IntegerField(verbose_name='DNI')),
                ('nombres_personal', models.CharField(max_length=20, verbose_name='Nombre de personal')),
                ('apellido_paterno_personal', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellido_materno_personal', models.CharField(max_length=20, verbose_name='Apellido Materno')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personals',
                'db_table': 'Personal',
                'ordering': ['apellido_paterno_personal', '-apellido_materno_personal'],
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_seguro', models.CharField(max_length=10, verbose_name='Tipo de Seguro')),
                ('abreviatura_seguro', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('estado_seguro', models.BooleanField(verbose_name='Estado seguro')),
            ],
            options={
                'verbose_name': 'Tipo de Seguro',
                'verbose_name_plural': 'Tipo de Seguro',
                'db_table': 'Seguro',
                'ordering': ['descripcion_seguro'],
            },
        ),
        migrations.CreateModel(
            name='Sexos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_sexo', models.CharField(max_length=10, verbose_name='Sexo')),
                ('estado_sexo', models.BooleanField(verbose_name='Condicion')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'db_table': 'Sexos',
                'ordering': ['descripcion_sexo'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipo_medico', models.CharField(max_length=20, verbose_name='Tipo Medico')),
                ('estado_tipo_medico', models.BooleanField(default=False, verbose_name='Estado Medico')),
            ],
            options={
                'verbose_name': 'Tipo de Medico',
                'verbose_name_plural': 'Tipo de Medico',
                'db_table': 'Tipo_Medico',
                'ordering': ['descripcion_tipo_medico'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8, verbose_name='dni')),
                ('nombres', models.CharField(max_length=20, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.CharField(max_length=20, verbose_name='Fecha de Nacimiento')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=11, verbose_name='Telefono')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('diagnostico', models.TextField(max_length=600, verbose_name='Diagnostico')),
                ('nacionalidad', models.CharField(max_length=20, verbose_name='Nacionalidad')),
                ('grado_instruccion', models.CharField(max_length=20, verbose_name='Grado de Instrucción')),
                ('ocupacion', models.CharField(max_length=20, verbose_name='ocupacion')),
                ('domicilio', models.CharField(max_length=30, verbose_name='Domicilio')),
                ('centro_trabajo', models.CharField(max_length=20, verbose_name='Centro de Trabajo')),
                ('direccion_laboral', models.CharField(max_length=30, verbose_name='Dirección del trabajo')),
                ('numero_Seguro', models.CharField(max_length=20, verbose_name='Número de seguro')),
                ('nombres_apellidos_Padre', models.CharField(max_length=20, verbose_name='Nombres de padre')),
                ('nombres_apellidos_Madre', models.CharField(max_length=20, verbose_name='Nombres de la Madre')),
                ('contacto_urgencia', models.CharField(max_length=20, verbose_name='Nombre de Contacto')),
                ('dirección_contacto', models.CharField(max_length=20, verbose_name='Dirección de Contacto')),
                ('parentesco', models.CharField(max_length=20, verbose_name='Parentesco')),
                ('estado_padre', models.CharField(max_length=10, verbose_name='Estado padre')),
                ('estado_madre', models.CharField(max_length=10, verbose_name='Estado madre')),
                ('estado_civi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.estado_civil')),
                ('lugar_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.lugar_nacimiento')),
                ('sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sexos')),
                ('tipo_Seguro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seguro')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Persona',
                'ordering': ['id', '-apellido_materno'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni_Medico', models.IntegerField(verbose_name='Id_Medico')),
                ('nombres_medico', models.CharField(max_length=20, verbose_name='Nombre Medico')),
                ('apeliido_paterno_medico', models.CharField(max_length=20, verbose_name='Nombre Medico')),
                ('apeliido_materno_medico', models.CharField(max_length=20, verbose_name='Nombre Medico')),
                ('colegiatura_medico', models.CharField(max_length=20, verbose_name='Colegiatura Medico')),
                ('tipo_medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tipo_medico')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'db_table': 'Medico',
                'ordering': ['id', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asistencia', models.BooleanField(default='0')),
                ('observaciones', models.TextField(max_length=20, verbose_name='Observaciones')),
                ('Personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.personal')),
                ('dni_medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.medico')),
                ('id_Citas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cita')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.persona')),
            ],
            options={
                'verbose_name': 'Detalle_Cita',
                'verbose_name_plural': 'Detalle_Citas',
                'db_table': 'Detalle_Cita',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('numero_certificado', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero de Certificado')),
                ('fecha_certificado', models.DateField(verbose_name='Fecha de Certificado')),
                ('estado_certificado', models.BooleanField(verbose_name='Estado')),
                ('dni_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.persona')),
                ('medico_certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.medico')),
                ('personal_cetificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.personal')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'Certificado',
                'ordering': ['numero_certificado'],
            },
        ),
    ]
